### ISSUE TITLE
Any support for fluent binding?

### ISSUE THREAD

**Issue by MrYossu** [svan-jansson/OneOf.Monads#1]
Just come across `OneOf` and am exploring the possibilities it offers. Been using a very small subset of LanguageExt for years, and realised that `OneOf` offers pretty much everything I use form that package, without the masses of stuff that I'm not clever enough to use!

This package seems to fill in the one gap that `OneOf` leaves in my requirements, ie the ability to bind the types. However, it only seems to support method syntax, not fluent syntax, which I much prefer.

For example, using the example on the repo's main page, I would like to be able to do something like this (air code, so the exact syntax could be incorrect)...

```c#
Option<int> option = 20;

var jim = from o in option
          from _1 in IsGreaterThan10
          from _2 in IsEven
          let o2 = o.ToString()
          let o3 = $"~{o2}~"
          select o3;

// Can then use `Match`, etc on `jim`.
```

However, I get a compiler error saying _Could not find an implementation of the query pattern for source type 'Option<int>'.  'Select' not found._

From my vague understanding of this stuff, I think it just needs `SelectMany`  implementing for the type, but I wouldn't know where to start with that.

Is there any chance this could be added to this excellent package?

**Comment by svan-jansson** [comment]
Interesting! I will take a look at adding support for this. Thanks for the suggestion.

**Comment by svan-jansson** [comment]
I have now done some tests with implementing `IEnumerable<T>` for `Option<T>`, and while your syntax example can be achieved, I think it adds some confusion to what `Option<T>` is. I.E. not an enumerable. It would also involve interpreting the existing functions as corresponding enumerable methods, which quickly becomes quite hacky.

However all monadic types in `OneOf.Monads` does currently support what I believe is generally considered fluent binding, with chainable `.Bind` etc. If you still feel like this should be added to the library, I'll be happy to review an implementation suggestion in a PR.

**Comment by MrYossu** [comment]
@svan-jansson Thanks for the reply.

> I think it adds some confusion to what Option<T> is. I.E. not an enumerable.
I understand what you mean, but in fact, `Option<T>` **is** indeed a type of `IEnumerable<T>`, it's just one where you happen to know that the sequence consists of exactly zero or one elements, as opposed to the more general `IEnumerable<T>` which can consist of any number.

Seen that way, pretty much all monads are `IEnumerable<T>`, which is why the monads in packages like [LanguageExt](https://github.com/louthy/language-ext/) (which takes all this stuff to a serious level) all support fluent syntax.

I came to this realisation after reading [Functional Programming in C#, by Enrico Buonanno](https://www.manning.com/books/functional-programming-in-c-sharp-second-edition) (many times before I understood it admittedly 😄). He explains this idea very well.

>It would also involve interpreting the existing functions as corresponding enumerable methods, which quickly becomes quite hacky.

Again, given that they are actually `IEnumerable<T>`, you're not really re-interpreting them at all.

Obviously, it's your package, and so your choice as to what you support, but as far as I can see, all that is needed is support for `Select` and `SelectMany`.  Users can then choose to ignore this extra (ie use the package as they already do), or take advantage of it by being bale to use fluent syntax. It's not like you're changing the direction, or adding any confusion.

Thanks again.
